### PR TITLE
Added Travis CI Support

### PR DESCRIPTION
**Pull request by moulikcipherX**
Resolved Issue #67

### CODE REVIEW

**Comment by jdxcode** [comment]
#67 does not mean adding travis to the project, it means adding travis as an option to the CLIs the generator creates

**Comment by moulikcipherX** [comment]
I will surely make it happen..

**Comment by moulikcipherX** [comment]
Can you please sir look my questio  in issue #167

**Comment by moulikcipherX** [comment]
Sir can you look at my question in issue #174

**Comment by moulikcipherX** [comment]
Hello, @jdxcode I have added Travis CI support. Please Review it

**Comment by moulikcipherX** [comment]
@rasphilco

**Pull request merged**
