### PR TITLE
Fix missing ACL declaration in version-indexes and promote

### LINKED ISSUE #884: The channel files and indexes miss public read ACL
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A bug.

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

Unlike `oclif upload`, `oclif promote` doesn't set `public-read` ACL. Therefore, every promotion breaks the channel.

On the build machine:

```
$ npx oclif pack tarballs
$ npx oclif upload tarballs
$ npx oclif promote --channel development --version 0.0.0-development --sha SHA --indexes
```

Then, on the client side:

```
❯ DEBUG=\* ./bin/mycli update --available
  http → GET https://BUCKET.s3.amazonaws.com/versions/mycli-darwin-arm64-tar-gz.json
  http ← GET https://BUCKET.s3.amazonaws.com/versions/mycli-darwin-arm64-tar-gz.json 403
  http   '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5WDFSGNJ6JQQXWH1</RequestId><HostId>N+cLoMqEr8NCqfi/+s3qMOrQahnP+E4SqOFwL3bT06kMu+wJOLaDlUGrOP+LxVITOUAwRbbh7PU=</HostId></Error>' +157ms
Error: No version indices exist for mycli.
```

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

`oclif promote` should set `public-read` ACL like `oclif upload`.

### `oclif upload`
https://github.com/oclif/oclif/blob/c26946d64a1b3c8702fd71b92010f1006970c7ff/src/commands/upload/tarballs.ts#L37-L40

### `oclif promote`
https://github.com/oclif/oclif/blob/e9d89f567abbbba72fd0da4641d131bf703e77c7/src/commands/promote.ts#L60-L68
https://github.com/oclif/oclif/blob/e9d89f567abbbba72fd0da4641d131bf703e77c7/src/version-indexes.ts#L68-L72

```
$ npx oclif --version
oclif/3.0.1 linux-x64 node-v16.14.0
```

### PR DESCRIPTION
**Pull request by truesteps**
closes #884

### CODE REVIEW

**Comment by truesteps** [comment]
I signed the CLA, it says it's signed but it threw some error and I guess the label didn't change

**Comment by riywo** [comment]
Any update from oclif team?

**Comment by truesteps** [comment]
Heya! Any update?

**Comment by truesteps** [comment]
Fetched upstream now all tests pass :) thanks for fixing the tests

**Comment by truesteps** [comment]
bump

**Review by RodEsp — APPROVED** [review]

**Comment by RodEsp** [comment]
Heya, sorry this went unnoticed for such a long time! Looks great though, thank you!

**Pull request merged**
