### PR TITLE
Add jest as alternative to mocha

### LINKED ISSUE #173: Add Jest as test alternative to Mocha
**Feature request**

Add Jest as test alternative to Mocha
https://jestjs.io/

### PR DESCRIPTION
**Pull request by sourabh1031**
fixes #173

### CODE REVIEW

**Comment by jdxcode** [comment]
where are the jest tests?

**Comment by sourabh1031** [comment]
@jdxcode do i need to write tests as well .? But the issue says that we need to add jest as option for testing

**Comment by jdxcode** [comment]
The generated CLI would need to include jest examples like we have for mocha

**Comment by sourabh1031** [comment]
@jdxcode please review i have updated the changes

**Comment by jdxcode** [comment]
This still doesn't add jest to the generated CLI. The generated CLI would need to use jest like it does for [mocha](https://github.com/oclif/example-multi-ts/blob/master/test/commands/hello.test.ts).

**Comment by sourabh1031** [comment]
@jdxcode update : i am currently reading the whole documentation so i will send the pr soon

**Comment by sourabh1031** [comment]
do i need to write test here in this folder  https://github.com/oclif/example-multi-ts/tree/master/test/commands
actually it contains test written by mocha and if i write in jest as well the name of the files would be same as per the convention of naming the test file

**Comment by sourabh1031** [comment]
i have written the tests please see https://github.com/oclif/example-multi-ts/pull/32

**Comment by sourabh1031** [comment]
@jdxcode can fancy test work on top of jest. actually i have looked over the web and not able to find any resources to learn from

**Comment by sourabh1031** [comment]
@jdxcode please review . i have made two separate directories mocha and jest in test directory and accordingly changed the path.

**Comment by sourabh1031** [comment]
@jdxcode @RasPhilCo i have done a major change . it necessarily requires your review so please do this

**Comment by zoltan-nz** [comment]
@sourabh1031 Looks great, thanks for your hard work. I suppose this PR should be rebased from the latest `master` and fix the failing tests. Hope after that maintainers will be reviewed and merge...

**Comment by sourabh1031** [comment]
> @sourabh1031 Looks great, thanks for your hard work. I suppose this PR should be rebased from the latest `master` and fix the failing tests. Hope after that maintainers will be reviewed and merge...

Thanks @zoltan-nz for your kind review

**Comment by sthuber90** [comment]
Are there any plans on merging this PR soon?

**Comment by zhawtof** [comment]
Following up from the previous comment. Is this PR going to be merged soon? Maybe an owner of this repo can make updates on behalf of the author?

**Comment by RasPhilCo** [comment]
@zhawtof this PR looks stale. Would advise anyone else who wants Jest support to pick it up or start a new PR. Note though, `fancy-test` uses mocha.

**Comment by G-Rath** [comment]
@RasPhilCo I would be happy to pick up this PR if you wouldn't mind giving it a review and requesting changes :)

I've not got enough free time to do a massive deep dive into the inner workings of oclif, but having given this PR a glance, it seems like it is almost there?

Hence, if you can give me direction on where what's needed to get this across the line, I'm happy to do the coding.

**Comment by MrStLouis** [comment]
any updates on this?

**Comment by felipecassiors** [comment]
What's the issue with Jest? I'm able to run `@oclif/test`'s `test` (which comes from  `fancy-test`) with no problem with Jest.

**Comment by RasPhilCo** [comment]
Closing due to age. If you think this is in error, please reply.

**Pull request closed without merging**
