### PR TITLE
Add more inclusive language to README

### LINKED ISSUE #311: More inclusive language in documentation
:wave: Sorry I know I'm ignoring your well-thought-out template, but hear me out...

I noticed that there are a couple of instances of words like "easy" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing or replacing instances of "simply", "easy", "just", etc. We use oclif in many [Unmock](https://github.com/unmock) projects so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

### PR DESCRIPTION
**Pull request by carolstran**
Closes #311 

As discussed in the issue, this PR attempts to remove or replace as many instances of condescending or isolating language (ie. simple, easy, just, etc) as possible in the documentation.

There are some instances where a change wasn't _necessary_ but I still felt like it would be beneficial, but of course, feel free to revert. If even a fraction of these changes can be merged then it will be a huge step towards making this repo more inclusive!

Next step (if it's alright): Tackling https://github.com/oclif/oclif.github.io

### CODE REVIEW

**Comment by RasPhilCo** [comment]
"Condescending" is a bit harsh of an adjective here and implies malintent. "Add more inclusive language to README" is vastly more accurate and appropriate.

**Comment by ORESoftware** [comment]
faciliate interpersonal understanding through the use of colorful dialectic

**Comment by carolstran** [comment]
@RasPhilCo While I don't think that the term `condescending` implies bad intent, I understand your point and changed the PR name accordingly 😇

**Comment by carolstran** [comment]
Question for any of the maintainers: Why did you decide to implement a CLA? We're debating it currently at my company so any insights are appreciated 😊

**Comment by RasPhilCo** [comment]
@carolstran thanks for the PR! The CLA is a Salesforce requirement for outside open source contributions. I don't know the legal reasons but can direct you to someone inside Salesforce if you'd like.

**Pull request merged**
