### PR TITLE
Adding oclif logo to README

### PR DESCRIPTION
**Pull request by schaar**
Let's add the `oclif` image to the README, similar to how it's done on https://github.com/atom/atom/blob/master/README.md.

I don't have access to the image, but put a placeholder where it should likely go. 👍

### CODE REVIEW

**Comment by schaar** [comment]
@jdxcode how's this look?

**Comment by jdxcode** [comment]
looks great! thanks!

**Comment by schaar** [comment]
@jdxcode Excellent - looks like I don't have write access so feel free to 🚢 the PR.

**Comment by jdxcode** [comment]
@schaar could you get me another image we could use for the [org](https://github.com/oclif)? I'm thinking maybe the same thing but with the colors reversed

**Comment by schaar** [comment]
@jdxcode sure - I'll ask Charlie to help out with generating one!

**Comment by superhighfives** [comment]
No worries! Here you are, @jdxcode: 
oclif white
oclif white 2x

**Comment by jdxcode** [comment]
updated! thanks so much!

**Pull request merged**
