### PR TITLE
fix: Update hooks generator to point to ./dist/hooks instead of ./src/hooks

### PR DESCRIPTION
**Pull request by jercle**
This will resolve https://github.com/oclif/oclif/issues/902

This does not change where the hooks are saved to as that is done on line 33, it only updates the path in package.json for the end user's cli being built

### CODE REVIEW

**Comment by truesteps** [comment]
if you fetch upstream in your repo tests will pass :), I also noticed hooks not working, thanks for the fix, let's hope the devs merge this

**Comment by jercle** [comment]
> if you fetch upstream in your repo tests will pass :), I also noticed hooks not working, thanks for the fix, let's hope the devs merge this

Cheers! Didn't even think hey. Have been a bit under the weather

**Comment by mdonnalley** [comment]
@jercle @truesteps Can you describe the issue you're seeing with using the `src` path?

I just tested this with the following and it works as expected

- `npx oclif generate my-cli`
- `cd my-cli`
- `npx ocli generate hook my_hook --event init`
- `bin/dev hello world --from me`

```
~/code/my-cli » bin/dev hello world --from me                                                                                                                                                                                                    
example hook running hello:world
hello world! (./src/commands/hello/world.ts)
```

**Comment by mdonnalley** [comment]
Never mind - I see the issue now. `bin/dev` knows how to work with the `src` path but `bin/run` doesn't

I'll merge this PR. Thanks for the contribution!

**Pull request merged**
