### PR TITLE
Modify README.md

### LINKED ISSUE #140: Node package recommendation question
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Documentation "bug" possibly.

What is the current behavior?
-----------------------------

It is advised that one can simply add the node package to the deps, and users will be running the latest node.  This doesn't seem totally correct though.

> You can add the node package to your CLI to ensure users are on Node 8.

This will only be true when your cli is run from a script field or a tool like npx, not when installed globally or used through the shebang bin file.

What is the expected behavior?
------------------------------
The current wording makes it sound like a generalized solution when it isn't.  Perhaps we should clarify where this works and doesn't work?

### PR DESCRIPTION
**Pull request by sourabh1031**
fixes #140

### CODE REVIEW

**Comment by sourabh1031** [comment]
@jdxcode @RasPhilCo please review

**Comment by sourabh1031** [comment]
and one more thing i got a nice article on the web
 https://medium.com/the-z/getting-started-with-oclif-by-creating-a-todo-cli-app-b3a2649adbcf . 
This is best to be included in the documentation itself. It will certainly help newbies to get started with oclif.

**Comment by sourabh1031** [comment]
@RasPhilCo @jdxcode please review

**Comment by RasPhilCo** [comment]
Closing due to age. If you think this is in error, please reply.

**Pull request closed without merging**
