### PR TITLE
Restore hook and command generators

### LINKED ISSUE #767: `command is not a oclif command` When trying to create a new command
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Possible bug

What is the current behavior?
-----------------------------
Run `oclif generate mynewcli`
`cd mynewcli`
Run `oclif command setup` to create a `setup` command

What is the expected behavior?
------------------------------
oclif/2.0.1 darwin-arm64 node-v14.18.0
Big Sur 11.6
When running `oclif command setup` I expect a new `setup` command to be scaffolded

### PR DESCRIPTION
**Pull request by mdonnalley**
- Restores the `hook` and `command` commands from v1 as `generate:hook` and `generate:command`, respectively. 
- Updates REAMDE with notes about migrating from v1 to v2

Fixes #767 

@W-10386078@

### CODE REVIEW

**Review by RodEsp — APPROVED** [review]

**Review by RodEsp — CHANGES_REQUESTED** [review]
QA
---
    ✅ `oclif generate:command mycommand`
      ✅ Creates a working command
      ✅ Creates a working test
      ✅ `--force` flag overwrites files
      ❌ `--defaults` flag doesn't do anything differently, not needed?
    ✅ `oclif generate:hook myhook` creates a working hook
      ✅ Creates a working hook
      ✅ Creates a working test
      ✅ `--force` flag overwrites files
      ✅ `--event customevent` flag correctly creates a hook under a custom event
      ❌  `--defaults` flag doesn't do anything differently, not needed?
      ❌ This always asks if you want to overwrite the `package.json`. 
          I assume it's because the file exists 
          but it would be a nicer user experience 
          if it only asked you that if the hook already existed and would be overwritten.

    Not sure if this is something we should fix but thought I'd throw it in here to get your thoughts.
    ❌ Running `oclif generate command` tries to generate a CLI called "command" instead of a command
    ❌ Same with `oclif generate hook`

**Comment by StevenLangbroek** [comment]
@RodEsp command generation, a primary functionality, is completely missing. It would appear restoring the preexisting functionality through a semver patch would take precedence over, and be considered separately from ergonomics improvements _to_ those commands, no? In your suggestions appear to be:

- a breaking change: `oclif generate command` should not result in a cli called `command`
- a bugfix: `--defaults` appears to be a noop, and can be deprecated
- an ergonomics improvement: `generate:hook` unnecessarily asks to overwrite package.json

I'd gladly contribute the changes you requested separately if @mdonnalley agrees and/or does not have time, energy or desire to do so.

Would love to hear your thoughts. Thanks 🙇

**Comment by RodEsp** [comment]
@StevenLangbroek, I do agree that restoring these commands is more important than command ergonomics but removing the `--defaults` flag should be so trivial we might as well get it done in this PR.

As for `oclif generate command` and `oclif generate hook` originally I thought it's not such a big deal but since you accurately pointed out that it'd be a breaking change I'd like to avoid having to release Oclif v3 immediately after we just released Oclif v2 if we can help it. With that in mind I'd like to at least explore if it's possible to fix this in this PR to avoid an unnecessary extra major version bump.

As far as having the time and energy to do so, both Mike and I are part of the Salesforce CLI team who actively maintains Oclif as part of our full time job. This PR is part of our current sprint cycle so no worries there. Always happy to accept contributions though so feel free to build on this existing branch if you'd like to speed us up! 🙏🏼

**Review by RodEsp — APPROVED** [review]

**Review by RodEsp — APPROVED** [review]
QA #2
---
Everything from QA above still works and
```
✅ `oclif generate command mycommand`
  ✅ Creates a working command
  ✅ Creates a working test
  ✅ `--force` flag overwrites files
✅ `oclif generate hook myhook` creates a working hook
  ✅ Creates a working hook
  ✅ Creates a working test
  ✅ `--force` flag overwrites files
  ✅ `--event customevent` flag correctly creates a hook under a custom event
```

**Comment by StevenLangbroek** [comment]
@RodEsp awesome :) question, those QA blocks, are those generated by SF internal tooling?

**Comment by StevenLangbroek** [comment]
@RodEsp got it, looks very cool, nice and concise!

**Pull request merged**
