### PR TITLE
feat doc multi subtopics enhancements

### PR DESCRIPTION
**Pull request by gaelmotte**
Fixes https://github.com/oclif/oclif/issues/1013

Changes : 
* Command `readme`:  add a `--multiNestedTopicsDepth=depth` flag
* Command `readme`: output doc accounts for topic separator other than `":"`

### CODE REVIEW

**Comment by gaelmotte** [comment]
Hi @mdonnalley,
You seem to be one of the most active contributors. Any chance you might have some time to review this ? :) 
If not, who should i ping ?

**Comment by Rinse12** [comment]
One of the features that set oclif aside from the rest of CLI libraries is its ability to generate readme, and this pull request will go far in enhancing it. If anyone is reading this and can merge it with the rest of the code base, it would be greatly appreciated.

**Comment by mdonnalley** [comment]
@gaelmotte Thanks for this PR and I'm sorry that it's taken so long to get around to it. Given that this is 1.5 yrs old and you're likely thinking about other things now, I'm going to take this over and get it merged (resolve merge conflicts, etc)

**Comment by gaelmotte** [comment]
Hi, 

Indeed, i moved on to other things.
But thank you for letting me know this little contribution got merged :)
Cheers !

**Pull request closed without merging**
